# #Info Configuration
tokenlines: 1
info: '{name}~mmoMinecraft~{coords}'
info2: ~~
info3: ~~
info4: ~~
HideDefaultHealthBar: false
HideDefaultExpBar: false
HideDefaultHungerBar: false
HideDefaultArmorBar: false
HideDefaultOxygenBar: false
