# #Info Configuration
tokenlines: 1
info: '{name}~mmoMinecraft~{coords}'
info2: ~~
info3: ~~
info4: ~~
HideDefaultHealthBar: true
HideDefaultExpBar: true
HideDefaultHungerBar: true
HideDefaultArmorBar: true
HideDefaultOxygenBar: false
