name: mmoInfo
version: ${releaseVersion} b${buildNumber}
description: Provides a modular info bar at the top of the screen.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Info.MMOInfo
depend: [Spout, mmoCore]

commands:
    info:
        description: Set the info to display
        aliases: [mmoinfo]
        usage: /info [three columns separated by ~, tokens within {}]

permissions:
    mmo.info:
        description: Access to all the mmoInfo display nodes
        default: true
    mmo.info.display:
        description: Shows the info bar
        default: true
